<?php

/**
 * @file
 * Provides the Trustpilot Carousel module custom functionality.
 */

/**
 * Implements hook_theme().
 */
function trustpilot_carousel_theme($existing, $type, $theme, $path) {
  return [
  // Note underscore, be consistent everywhere.
    'trustpilot_reviews' => [
      'variables' => [
        'reviews' => [],
      ],
      // trustpilot-reviews.html.twig file expected.
      'template' => 'trustpilot-reviews',
    ],
  ];
}
